# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zan/rpc/v1/common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'zan/rpc/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17zan/rpc/v1/common.proto\x12\nzan.rpc.v1\"H\n\x0cTraceContext\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x17\n\nsession_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\r\n\x0b_session_id*6\n\x04Lang\x12\x14\n\x10LANG_UNSPECIFIED\x10\x00\x12\x0b\n\x07LANG_RU\x10\x01\x12\x0b\n\x07LANG_KZ\x10\x02\x42\x30Z.zan-backend/internal/genproto/zan/rpc/v1;zanv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zan.rpc.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.zan-backend/internal/genproto/zan/rpc/v1;zanv1'
  _globals['_LANG']._serialized_start=113
  _globals['_LANG']._serialized_end=167
  _globals['_TRACECONTEXT']._serialized_start=39
  _globals['_TRACECONTEXT']._serialized_end=111
# @@protoc_insertion_point(module_scope)
