# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from zan.rpc.v1 import documents_pb2 as zan_dot_rpc_dot_v1_dot_documents__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in zan/rpc/v1/documents_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentsServiceStub:
    """DocumentsService — рендер документа из структурированного черновика
    (BACKEND_PLAN.md §3, Stage 4 — базовый рендер-пайплайн; вызывающий
    юзкейс "Агент Документы" — Stage 6). Всегда возвращает ссылку на готовый
    файл, никогда бинарь (BACKEND_PLAN.md §3.1) — закрывает двусмысленность
    исходного HTTP-варианта контракта одним явным вариантом.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Render = channel.unary_unary(
                '/zan.rpc.v1.DocumentsService/Render',
                request_serializer=zan_dot_rpc_dot_v1_dot_documents__pb2.RenderRequest.SerializeToString,
                response_deserializer=zan_dot_rpc_dot_v1_dot_documents__pb2.RenderResponse.FromString,
                _registered_method=True)


class DocumentsServiceServicer:
    """DocumentsService — рендер документа из структурированного черновика
    (BACKEND_PLAN.md §3, Stage 4 — базовый рендер-пайплайн; вызывающий
    юзкейс "Агент Документы" — Stage 6). Всегда возвращает ссылку на готовый
    файл, никогда бинарь (BACKEND_PLAN.md §3.1) — закрывает двусмысленность
    исходного HTTP-варианта контракта одним явным вариантом.
    """

    def Render(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Render': grpc.unary_unary_rpc_method_handler(
                    servicer.Render,
                    request_deserializer=zan_dot_rpc_dot_v1_dot_documents__pb2.RenderRequest.FromString,
                    response_serializer=zan_dot_rpc_dot_v1_dot_documents__pb2.RenderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zan.rpc.v1.DocumentsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zan.rpc.v1.DocumentsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentsService:
    """DocumentsService — рендер документа из структурированного черновика
    (BACKEND_PLAN.md §3, Stage 4 — базовый рендер-пайплайн; вызывающий
    юзкейс "Агент Документы" — Stage 6). Всегда возвращает ссылку на готовый
    файл, никогда бинарь (BACKEND_PLAN.md §3.1) — закрывает двусмысленность
    исходного HTTP-варианта контракта одним явным вариантом.
    """

    @staticmethod
    def Render(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zan.rpc.v1.DocumentsService/Render',
            zan_dot_rpc_dot_v1_dot_documents__pb2.RenderRequest.SerializeToString,
            zan_dot_rpc_dot_v1_dot_documents__pb2.RenderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
