# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zan/rpc/v1/documents.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'zan/rpc/v1/documents.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1azan/rpc/v1/documents.proto\x12\nzan.rpc.v1\".\n\x0f\x44ocumentSection\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t\"w\n\rRenderRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12-\n\x08sections\x18\x02 \x03(\x0b\x32\x1b.zan.rpc.v1.DocumentSection\x12(\n\x06\x66ormat\x18\x03 \x01(\x0e\x32\x18.zan.rpc.v1.RenderFormat\"6\n\x0eRenderResponse\x12\x10\n\x08\x66ile_url\x18\x01 \x01(\t\x12\x12\n\nobject_key\x18\x02 \x01(\t*\\\n\x0cRenderFormat\x12\x1d\n\x19RENDER_FORMAT_UNSPECIFIED\x10\x00\x12\x15\n\x11RENDER_FORMAT_PDF\x10\x01\x12\x16\n\x12RENDER_FORMAT_DOCX\x10\x02\x32S\n\x10\x44ocumentsService\x12?\n\x06Render\x12\x19.zan.rpc.v1.RenderRequest\x1a\x1a.zan.rpc.v1.RenderResponseB0Z.zan-backend/internal/genproto/zan/rpc/v1;zanv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zan.rpc.v1.documents_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.zan-backend/internal/genproto/zan/rpc/v1;zanv1'
  _globals['_RENDERFORMAT']._serialized_start=267
  _globals['_RENDERFORMAT']._serialized_end=359
  _globals['_DOCUMENTSECTION']._serialized_start=42
  _globals['_DOCUMENTSECTION']._serialized_end=88
  _globals['_RENDERREQUEST']._serialized_start=90
  _globals['_RENDERREQUEST']._serialized_end=209
  _globals['_RENDERRESPONSE']._serialized_start=211
  _globals['_RENDERRESPONSE']._serialized_end=265
  _globals['_DOCUMENTSSERVICE']._serialized_start=361
  _globals['_DOCUMENTSSERVICE']._serialized_end=444
# @@protoc_insertion_point(module_scope)
