# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from zan.rpc.v1 import files_pb2 as zan_dot_rpc_dot_v1_dot_files__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in zan/rpc/v1/files_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FilesServiceStub:
    """FilesService — операции над уже сохранёнными в S3-совместимом хранилище
    файлами, оба RPC синхронные. Extract — извлечение текста вложения
    (BACKEND_PLAN.md §3, Stage 4; backend/internal/service/file сразу после
    сохранения файла). ConvertToPdf — PDF-копия DOCX-шаблона документа для
    просмотра в админке (backend/internal/service/template).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Extract = channel.unary_unary(
                '/zan.rpc.v1.FilesService/Extract',
                request_serializer=zan_dot_rpc_dot_v1_dot_files__pb2.ExtractRequest.SerializeToString,
                response_deserializer=zan_dot_rpc_dot_v1_dot_files__pb2.ExtractResponse.FromString,
                _registered_method=True)
        self.ConvertToPdf = channel.unary_unary(
                '/zan.rpc.v1.FilesService/ConvertToPdf',
                request_serializer=zan_dot_rpc_dot_v1_dot_files__pb2.ConvertToPdfRequest.SerializeToString,
                response_deserializer=zan_dot_rpc_dot_v1_dot_files__pb2.ConvertToPdfResponse.FromString,
                _registered_method=True)


class FilesServiceServicer:
    """FilesService — операции над уже сохранёнными в S3-совместимом хранилище
    файлами, оба RPC синхронные. Extract — извлечение текста вложения
    (BACKEND_PLAN.md §3, Stage 4; backend/internal/service/file сразу после
    сохранения файла). ConvertToPdf — PDF-копия DOCX-шаблона документа для
    просмотра в админке (backend/internal/service/template).
    """

    def Extract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertToPdf(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FilesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Extract': grpc.unary_unary_rpc_method_handler(
                    servicer.Extract,
                    request_deserializer=zan_dot_rpc_dot_v1_dot_files__pb2.ExtractRequest.FromString,
                    response_serializer=zan_dot_rpc_dot_v1_dot_files__pb2.ExtractResponse.SerializeToString,
            ),
            'ConvertToPdf': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertToPdf,
                    request_deserializer=zan_dot_rpc_dot_v1_dot_files__pb2.ConvertToPdfRequest.FromString,
                    response_serializer=zan_dot_rpc_dot_v1_dot_files__pb2.ConvertToPdfResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zan.rpc.v1.FilesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zan.rpc.v1.FilesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FilesService:
    """FilesService — операции над уже сохранёнными в S3-совместимом хранилище
    файлами, оба RPC синхронные. Extract — извлечение текста вложения
    (BACKEND_PLAN.md §3, Stage 4; backend/internal/service/file сразу после
    сохранения файла). ConvertToPdf — PDF-копия DOCX-шаблона документа для
    просмотра в админке (backend/internal/service/template).
    """

    @staticmethod
    def Extract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zan.rpc.v1.FilesService/Extract',
            zan_dot_rpc_dot_v1_dot_files__pb2.ExtractRequest.SerializeToString,
            zan_dot_rpc_dot_v1_dot_files__pb2.ExtractResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConvertToPdf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zan.rpc.v1.FilesService/ConvertToPdf',
            zan_dot_rpc_dot_v1_dot_files__pb2.ConvertToPdfRequest.SerializeToString,
            zan_dot_rpc_dot_v1_dot_files__pb2.ConvertToPdfResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
