# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zan/rpc/v1/rag.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'zan/rpc/v1/rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14zan/rpc/v1/rag.proto\x12\nzan.rpc.v1\"2\n\rSearchRequest\x12\x12\n\nquery_text\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"8\n\x0bSearchMatch\x12\x0b\n\x03ref\x18\x01 \x01(\t\x12\r\n\x05quote\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\":\n\x0eSearchResponse\x12(\n\x07matches\x18\x01 \x03(\x0b\x32\x17.zan.rpc.v1.SearchMatch2M\n\nRagService\x12?\n\x06Search\x12\x19.zan.rpc.v1.SearchRequest\x1a\x1a.zan.rpc.v1.SearchResponseB0Z.zan-backend/internal/genproto/zan/rpc/v1;zanv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zan.rpc.v1.rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.zan-backend/internal/genproto/zan/rpc/v1;zanv1'
  _globals['_SEARCHREQUEST']._serialized_start=36
  _globals['_SEARCHREQUEST']._serialized_end=86
  _globals['_SEARCHMATCH']._serialized_start=88
  _globals['_SEARCHMATCH']._serialized_end=144
  _globals['_SEARCHRESPONSE']._serialized_start=146
  _globals['_SEARCHRESPONSE']._serialized_end=204
  _globals['_RAGSERVICE']._serialized_start=206
  _globals['_RAGSERVICE']._serialized_end=283
# @@protoc_insertion_point(module_scope)
