# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from zan.rpc.v1 import stt_pb2 as zan_dot_rpc_dot_v1_dot_stt__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in zan/rpc/v1/stt_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SttServiceStub:
    """SttService — распознавание речи (BACKEND_PLAN.md §3, Stage 4). Вызывается
    синхронно из POST /voice/transcribe (zan-backend-tz-v2.md §4.7) — клиент
    ждёт текст до отправки сообщения в тред.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.unary_unary(
                '/zan.rpc.v1.SttService/Transcribe',
                request_serializer=zan_dot_rpc_dot_v1_dot_stt__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=zan_dot_rpc_dot_v1_dot_stt__pb2.TranscribeResponse.FromString,
                _registered_method=True)


class SttServiceServicer:
    """SttService — распознавание речи (BACKEND_PLAN.md §3, Stage 4). Вызывается
    синхронно из POST /voice/transcribe (zan-backend-tz-v2.md §4.7) — клиент
    ждёт текст до отправки сообщения в тред.
    """

    def Transcribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SttServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=zan_dot_rpc_dot_v1_dot_stt__pb2.TranscribeRequest.FromString,
                    response_serializer=zan_dot_rpc_dot_v1_dot_stt__pb2.TranscribeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zan.rpc.v1.SttService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zan.rpc.v1.SttService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SttService:
    """SttService — распознавание речи (BACKEND_PLAN.md §3, Stage 4). Вызывается
    синхронно из POST /voice/transcribe (zan-backend-tz-v2.md §4.7) — клиент
    ждёт текст до отправки сообщения в тред.
    """

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zan.rpc.v1.SttService/Transcribe',
            zan_dot_rpc_dot_v1_dot_stt__pb2.TranscribeRequest.SerializeToString,
            zan_dot_rpc_dot_v1_dot_stt__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
