# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zan/rpc/v1/stt.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'zan/rpc/v1/stt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zan.rpc.v1 import common_pb2 as zan_dot_rpc_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14zan/rpc/v1/stt.proto\x12\nzan.rpc.v1\x1a\x17zan/rpc/v1/common.proto\"X\n\x11TranscribeRequest\x12\x10\n\x08\x66ile_url\x18\x01 \x01(\t\x12\x11\n\tmime_type\x18\x02 \x01(\t\x12\x1e\n\x04lang\x18\x03 \x01(\x0e\x32\x10.zan.rpc.v1.Lang\"\"\n\x12TranscribeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2Y\n\nSttService\x12K\n\nTranscribe\x12\x1d.zan.rpc.v1.TranscribeRequest\x1a\x1e.zan.rpc.v1.TranscribeResponseB0Z.zan-backend/internal/genproto/zan/rpc/v1;zanv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zan.rpc.v1.stt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.zan-backend/internal/genproto/zan/rpc/v1;zanv1'
  _globals['_TRANSCRIBEREQUEST']._serialized_start=61
  _globals['_TRANSCRIBEREQUEST']._serialized_end=149
  _globals['_TRANSCRIBERESPONSE']._serialized_start=151
  _globals['_TRANSCRIBERESPONSE']._serialized_end=185
  _globals['_STTSERVICE']._serialized_start=187
  _globals['_STTSERVICE']._serialized_end=276
# @@protoc_insertion_point(module_scope)
