// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: zan/rpc/v1/common.proto

// Пакет назывался "zan.internal.v1" (директория proto/zan/internal/v1/) до
// Stage 4 — переименован в "zan.rpc.v1", т.к. buf генерирует Go-код с
// paths=source_relative (backend/internal/genproto/<путь .proto файла>), и
// директория "internal" ВНУТРИ уже-internal `backend/internal/` создавала
// собственную Go-границу видимости: сгенерированный пакет оказывался
// импортируемым только из кода под .../genproto/zan/..., а не из остального
// backend/internal/* (обнаружено при первой попытке импортировать
// сгенерированный клиент из internal/grpcclient — см. BACKEND_LOG.md,
// Stage 4). "internal" как имя директории — зарезервированное для Go слово,
// не стоит использовать его повторно внутри уже-internal дерева.

package zanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lang — предпочитаемый язык сессии (domain.Language в Go,
// zan-backend-tz-v3.md §2.2), передаётся туда, где Python-стороне нужен
// языковой контекст (SttService.Transcribe — Stage 4; RagService.Search —
// Stage 5). Первый потребитель — stt.proto.
type Lang int32

const (
	Lang_LANG_UNSPECIFIED Lang = 0
	Lang_LANG_RU          Lang = 1
	Lang_LANG_KZ          Lang = 2
)

// Enum value maps for Lang.
var (
	Lang_name = map[int32]string{
		0: "LANG_UNSPECIFIED",
		1: "LANG_RU",
		2: "LANG_KZ",
	}
	Lang_value = map[string]int32{
		"LANG_UNSPECIFIED": 0,
		"LANG_RU":          1,
		"LANG_KZ":          2,
	}
)

func (x Lang) Enum() *Lang {
	p := new(Lang)
	*p = x
	return p
}

func (x Lang) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Lang) Descriptor() protoreflect.EnumDescriptor {
	return file_zan_rpc_v1_common_proto_enumTypes[0].Descriptor()
}

func (Lang) Type() protoreflect.EnumType {
	return &file_zan_rpc_v1_common_proto_enumTypes[0]
}

func (x Lang) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Lang.Descriptor instead.
func (Lang) EnumDescriptor() ([]byte, []int) {
	return file_zan_rpc_v1_common_proto_rawDescGZIP(), []int{0}
}

// TraceContext — сквозной идентификатор запроса, прикладывается ко всем
// будущим RPC-запросам Go -> Python (RagService/FilesService/DocumentsService/
// SttService, см. BACKEND_PLAN.md §3). trace_id совпадает с X-Trace-Id,
// который фронт шлёт на Go (BACKEND_CODING_STANDARDS.md §4.3).
//
// На Stage 0 сообщение ничем не использовалось — только проверяло, что
// кодогенерация Go/Python работает end-to-end на общем .proto (DoD Stage 0,
// BACKEND_PLAN.md). trace_id/session_id по-прежнему передаются в
// gRPC-метадате клиентским interceptor'ом (internal/grpcclient), не через
// это сообщение — см. BACKEND_LOG.md, запись Stage 0 (#71). Остальные общие
// типы добавляются сюда по мере появления первого реального RPC, которому
// они нужны — не заводятся заранее "про запас".
type TraceContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SessionId     *string                `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceContext) Reset() {
	*x = TraceContext{}
	mi := &file_zan_rpc_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceContext) ProtoMessage() {}

func (x *TraceContext) ProtoReflect() protoreflect.Message {
	mi := &file_zan_rpc_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceContext.ProtoReflect.Descriptor instead.
func (*TraceContext) Descriptor() ([]byte, []int) {
	return file_zan_rpc_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *TraceContext) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TraceContext) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

var File_zan_rpc_v1_common_proto protoreflect.FileDescriptor

const file_zan_rpc_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x17zan/rpc/v1/common.proto\x12\n" +
	"zan.rpc.v1\"\\\n" +
	"\fTraceContext\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\"\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tH\x00R\tsessionId\x88\x01\x01B\r\n" +
	"\v_session_id*6\n" +
	"\x04Lang\x12\x14\n" +
	"\x10LANG_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aLANG_RU\x10\x01\x12\v\n" +
	"\aLANG_KZ\x10\x02B0Z.zan-backend/internal/genproto/zan/rpc/v1;zanv1b\x06proto3"

var (
	file_zan_rpc_v1_common_proto_rawDescOnce sync.Once
	file_zan_rpc_v1_common_proto_rawDescData []byte
)

func file_zan_rpc_v1_common_proto_rawDescGZIP() []byte {
	file_zan_rpc_v1_common_proto_rawDescOnce.Do(func() {
		file_zan_rpc_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zan_rpc_v1_common_proto_rawDesc), len(file_zan_rpc_v1_common_proto_rawDesc)))
	})
	return file_zan_rpc_v1_common_proto_rawDescData
}

var file_zan_rpc_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_zan_rpc_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_zan_rpc_v1_common_proto_goTypes = []any{
	(Lang)(0),            // 0: zan.rpc.v1.Lang
	(*TraceContext)(nil), // 1: zan.rpc.v1.TraceContext
}
var file_zan_rpc_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zan_rpc_v1_common_proto_init() }
func file_zan_rpc_v1_common_proto_init() {
	if File_zan_rpc_v1_common_proto != nil {
		return
	}
	file_zan_rpc_v1_common_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zan_rpc_v1_common_proto_rawDesc), len(file_zan_rpc_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zan_rpc_v1_common_proto_goTypes,
		DependencyIndexes: file_zan_rpc_v1_common_proto_depIdxs,
		EnumInfos:         file_zan_rpc_v1_common_proto_enumTypes,
		MessageInfos:      file_zan_rpc_v1_common_proto_msgTypes,
	}.Build()
	File_zan_rpc_v1_common_proto = out.File
	file_zan_rpc_v1_common_proto_goTypes = nil
	file_zan_rpc_v1_common_proto_depIdxs = nil
}
