// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: zan/rpc/v1/documents.proto

package zanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RenderFormat int32

const (
	RenderFormat_RENDER_FORMAT_UNSPECIFIED RenderFormat = 0
	RenderFormat_RENDER_FORMAT_PDF         RenderFormat = 1
	RenderFormat_RENDER_FORMAT_DOCX        RenderFormat = 2
)

// Enum value maps for RenderFormat.
var (
	RenderFormat_name = map[int32]string{
		0: "RENDER_FORMAT_UNSPECIFIED",
		1: "RENDER_FORMAT_PDF",
		2: "RENDER_FORMAT_DOCX",
	}
	RenderFormat_value = map[string]int32{
		"RENDER_FORMAT_UNSPECIFIED": 0,
		"RENDER_FORMAT_PDF":         1,
		"RENDER_FORMAT_DOCX":        2,
	}
)

func (x RenderFormat) Enum() *RenderFormat {
	p := new(RenderFormat)
	*p = x
	return p
}

func (x RenderFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RenderFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_zan_rpc_v1_documents_proto_enumTypes[0].Descriptor()
}

func (RenderFormat) Type() protoreflect.EnumType {
	return &file_zan_rpc_v1_documents_proto_enumTypes[0]
}

func (x RenderFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RenderFormat.Descriptor instead.
func (RenderFormat) EnumDescriptor() ([]byte, []int) {
	return file_zan_rpc_v1_documents_proto_rawDescGZIP(), []int{0}
}

// DocumentSection — та же форма, что domain.Finding в Go (zan-backend-tz-v2.md
// §2.7: `[{title, body}]`) — черновик документа собирается из тех же
// структурированных находок, которые агент уже возвращает в чат.
type DocumentSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentSection) Reset() {
	*x = DocumentSection{}
	mi := &file_zan_rpc_v1_documents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentSection) ProtoMessage() {}

func (x *DocumentSection) ProtoReflect() protoreflect.Message {
	mi := &file_zan_rpc_v1_documents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentSection.ProtoReflect.Descriptor instead.
func (*DocumentSection) Descriptor() ([]byte, []int) {
	return file_zan_rpc_v1_documents_proto_rawDescGZIP(), []int{0}
}

func (x *DocumentSection) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocumentSection) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type RenderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Sections      []*DocumentSection     `protobuf:"bytes,2,rep,name=sections,proto3" json:"sections,omitempty"`
	Format        RenderFormat           `protobuf:"varint,3,opt,name=format,proto3,enum=zan.rpc.v1.RenderFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderRequest) Reset() {
	*x = RenderRequest{}
	mi := &file_zan_rpc_v1_documents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderRequest) ProtoMessage() {}

func (x *RenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zan_rpc_v1_documents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderRequest.ProtoReflect.Descriptor instead.
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return file_zan_rpc_v1_documents_proto_rawDescGZIP(), []int{1}
}

func (x *RenderRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RenderRequest) GetSections() []*DocumentSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

func (x *RenderRequest) GetFormat() RenderFormat {
	if x != nil {
		return x.Format
	}
	return RenderFormat_RENDER_FORMAT_UNSPECIFIED
}

// RenderResponse — file_url готов к немедленной отдаче клиенту (presigned,
// короткого времени жизни); object_key — стабильная ссылка на объект в
// хранилище для того, кто должен пережить истечение presigned-ссылки и
// перевыпустить свежую позже (Stage 6: FileAttachment(purpose=generated_output)
// хранит именно object_key, не file_url).
type RenderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUrl       string                 `protobuf:"bytes,1,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderResponse) Reset() {
	*x = RenderResponse{}
	mi := &file_zan_rpc_v1_documents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderResponse) ProtoMessage() {}

func (x *RenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zan_rpc_v1_documents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderResponse.ProtoReflect.Descriptor instead.
func (*RenderResponse) Descriptor() ([]byte, []int) {
	return file_zan_rpc_v1_documents_proto_rawDescGZIP(), []int{2}
}

func (x *RenderResponse) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *RenderResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

var File_zan_rpc_v1_documents_proto protoreflect.FileDescriptor

const file_zan_rpc_v1_documents_proto_rawDesc = "" +
	"\n" +
	"\x1azan/rpc/v1/documents.proto\x12\n" +
	"zan.rpc.v1\";\n" +
	"\x0fDocumentSection\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\"\x90\x01\n" +
	"\rRenderRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x127\n" +
	"\bsections\x18\x02 \x03(\v2\x1b.zan.rpc.v1.DocumentSectionR\bsections\x120\n" +
	"\x06format\x18\x03 \x01(\x0e2\x18.zan.rpc.v1.RenderFormatR\x06format\"J\n" +
	"\x0eRenderResponse\x12\x19\n" +
	"\bfile_url\x18\x01 \x01(\tR\afileUrl\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey*\\\n" +
	"\fRenderFormat\x12\x1d\n" +
	"\x19RENDER_FORMAT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RENDER_FORMAT_PDF\x10\x01\x12\x16\n" +
	"\x12RENDER_FORMAT_DOCX\x10\x022S\n" +
	"\x10DocumentsService\x12?\n" +
	"\x06Render\x12\x19.zan.rpc.v1.RenderRequest\x1a\x1a.zan.rpc.v1.RenderResponseB0Z.zan-backend/internal/genproto/zan/rpc/v1;zanv1b\x06proto3"

var (
	file_zan_rpc_v1_documents_proto_rawDescOnce sync.Once
	file_zan_rpc_v1_documents_proto_rawDescData []byte
)

func file_zan_rpc_v1_documents_proto_rawDescGZIP() []byte {
	file_zan_rpc_v1_documents_proto_rawDescOnce.Do(func() {
		file_zan_rpc_v1_documents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zan_rpc_v1_documents_proto_rawDesc), len(file_zan_rpc_v1_documents_proto_rawDesc)))
	})
	return file_zan_rpc_v1_documents_proto_rawDescData
}

var file_zan_rpc_v1_documents_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_zan_rpc_v1_documents_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_zan_rpc_v1_documents_proto_goTypes = []any{
	(RenderFormat)(0),       // 0: zan.rpc.v1.RenderFormat
	(*DocumentSection)(nil), // 1: zan.rpc.v1.DocumentSection
	(*RenderRequest)(nil),   // 2: zan.rpc.v1.RenderRequest
	(*RenderResponse)(nil),  // 3: zan.rpc.v1.RenderResponse
}
var file_zan_rpc_v1_documents_proto_depIdxs = []int32{
	1, // 0: zan.rpc.v1.RenderRequest.sections:type_name -> zan.rpc.v1.DocumentSection
	0, // 1: zan.rpc.v1.RenderRequest.format:type_name -> zan.rpc.v1.RenderFormat
	2, // 2: zan.rpc.v1.DocumentsService.Render:input_type -> zan.rpc.v1.RenderRequest
	3, // 3: zan.rpc.v1.DocumentsService.Render:output_type -> zan.rpc.v1.RenderResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_zan_rpc_v1_documents_proto_init() }
func file_zan_rpc_v1_documents_proto_init() {
	if File_zan_rpc_v1_documents_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zan_rpc_v1_documents_proto_rawDesc), len(file_zan_rpc_v1_documents_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zan_rpc_v1_documents_proto_goTypes,
		DependencyIndexes: file_zan_rpc_v1_documents_proto_depIdxs,
		EnumInfos:         file_zan_rpc_v1_documents_proto_enumTypes,
		MessageInfos:      file_zan_rpc_v1_documents_proto_msgTypes,
	}.Build()
	File_zan_rpc_v1_documents_proto = out.File
	file_zan_rpc_v1_documents_proto_goTypes = nil
	file_zan_rpc_v1_documents_proto_depIdxs = nil
}
