// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: zan/rpc/v1/files.proto

package zanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExtractRequest — file_url, не байты (BACKEND_PLAN.md §3.1: payload
// остаётся маленьким, лимит unary-сообщения gRPC не бьёт при любом размере
// файла). file_url — presigned GET-ссылка на собственный MinIO/S3
// backend'а, короткого времени жизни (internal/grpcclient генерирует её
// непосредственно перед вызовом) — Python обязан проверить, что host
// ссылки совпадает с его собственным сконфигурированным storage-эндпоинтом,
// прежде чем идти по ней (SSRF-риск, BACKEND_PLAN.md §8).
type ExtractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUrl       string                 `protobuf:"bytes,1,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	mi := &file_zan_rpc_v1_files_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequest) ProtoMessage() {}

func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zan_rpc_v1_files_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequest.ProtoReflect.Descriptor instead.
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return file_zan_rpc_v1_files_proto_rawDescGZIP(), []int{0}
}

func (x *ExtractRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *ExtractRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type ExtractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractResponse) Reset() {
	*x = ExtractResponse{}
	mi := &file_zan_rpc_v1_files_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractResponse) ProtoMessage() {}

func (x *ExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zan_rpc_v1_files_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractResponse.ProtoReflect.Descriptor instead.
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return file_zan_rpc_v1_files_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// ConvertToPdfRequest — те же правила для file_url, что у ExtractRequest
// (presigned-ссылка на собственный storage, SSRF-проверка на стороне Python).
// mime_type — сейчас поддерживается только DOCX; остальное — INVALID_ARGUMENT.
type ConvertToPdfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUrl       string                 `protobuf:"bytes,1,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertToPdfRequest) Reset() {
	*x = ConvertToPdfRequest{}
	mi := &file_zan_rpc_v1_files_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertToPdfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertToPdfRequest) ProtoMessage() {}

func (x *ConvertToPdfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zan_rpc_v1_files_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertToPdfRequest.ProtoReflect.Descriptor instead.
func (*ConvertToPdfRequest) Descriptor() ([]byte, []int) {
	return file_zan_rpc_v1_files_proto_rawDescGZIP(), []int{2}
}

func (x *ConvertToPdfRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *ConvertToPdfRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

// ConvertToPdfResponse — ключ готового PDF в том же бакете (не ссылка и не
// байты, тот же принцип, что RenderResponse.object_key): владелец объекта
// дальше — backend/, он же перевыпускает ссылки и удаляет объект.
type ConvertToPdfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertToPdfResponse) Reset() {
	*x = ConvertToPdfResponse{}
	mi := &file_zan_rpc_v1_files_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertToPdfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertToPdfResponse) ProtoMessage() {}

func (x *ConvertToPdfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zan_rpc_v1_files_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertToPdfResponse.ProtoReflect.Descriptor instead.
func (*ConvertToPdfResponse) Descriptor() ([]byte, []int) {
	return file_zan_rpc_v1_files_proto_rawDescGZIP(), []int{3}
}

func (x *ConvertToPdfResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

var File_zan_rpc_v1_files_proto protoreflect.FileDescriptor

const file_zan_rpc_v1_files_proto_rawDesc = "" +
	"\n" +
	"\x16zan/rpc/v1/files.proto\x12\n" +
	"zan.rpc.v1\"H\n" +
	"\x0eExtractRequest\x12\x19\n" +
	"\bfile_url\x18\x01 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\"%\n" +
	"\x0fExtractResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"M\n" +
	"\x13ConvertToPdfRequest\x12\x19\n" +
	"\bfile_url\x18\x01 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\"5\n" +
	"\x14ConvertToPdfResponse\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey2\xa5\x01\n" +
	"\fFilesService\x12B\n" +
	"\aExtract\x12\x1a.zan.rpc.v1.ExtractRequest\x1a\x1b.zan.rpc.v1.ExtractResponse\x12Q\n" +
	"\fConvertToPdf\x12\x1f.zan.rpc.v1.ConvertToPdfRequest\x1a .zan.rpc.v1.ConvertToPdfResponseB0Z.zan-backend/internal/genproto/zan/rpc/v1;zanv1b\x06proto3"

var (
	file_zan_rpc_v1_files_proto_rawDescOnce sync.Once
	file_zan_rpc_v1_files_proto_rawDescData []byte
)

func file_zan_rpc_v1_files_proto_rawDescGZIP() []byte {
	file_zan_rpc_v1_files_proto_rawDescOnce.Do(func() {
		file_zan_rpc_v1_files_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zan_rpc_v1_files_proto_rawDesc), len(file_zan_rpc_v1_files_proto_rawDesc)))
	})
	return file_zan_rpc_v1_files_proto_rawDescData
}

var file_zan_rpc_v1_files_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_zan_rpc_v1_files_proto_goTypes = []any{
	(*ExtractRequest)(nil),       // 0: zan.rpc.v1.ExtractRequest
	(*ExtractResponse)(nil),      // 1: zan.rpc.v1.ExtractResponse
	(*ConvertToPdfRequest)(nil),  // 2: zan.rpc.v1.ConvertToPdfRequest
	(*ConvertToPdfResponse)(nil), // 3: zan.rpc.v1.ConvertToPdfResponse
}
var file_zan_rpc_v1_files_proto_depIdxs = []int32{
	0, // 0: zan.rpc.v1.FilesService.Extract:input_type -> zan.rpc.v1.ExtractRequest
	2, // 1: zan.rpc.v1.FilesService.ConvertToPdf:input_type -> zan.rpc.v1.ConvertToPdfRequest
	1, // 2: zan.rpc.v1.FilesService.Extract:output_type -> zan.rpc.v1.ExtractResponse
	3, // 3: zan.rpc.v1.FilesService.ConvertToPdf:output_type -> zan.rpc.v1.ConvertToPdfResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zan_rpc_v1_files_proto_init() }
func file_zan_rpc_v1_files_proto_init() {
	if File_zan_rpc_v1_files_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zan_rpc_v1_files_proto_rawDesc), len(file_zan_rpc_v1_files_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zan_rpc_v1_files_proto_goTypes,
		DependencyIndexes: file_zan_rpc_v1_files_proto_depIdxs,
		MessageInfos:      file_zan_rpc_v1_files_proto_msgTypes,
	}.Build()
	File_zan_rpc_v1_files_proto = out.File
	file_zan_rpc_v1_files_proto_goTypes = nil
	file_zan_rpc_v1_files_proto_depIdxs = nil
}
