// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: zan/rpc/v1/rag.proto

package zanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SearchRequest.query_text — текст вопроса (+ конкатенированный контекст
// треда собирает вызывающая сторона, internal/agent, до вызова — сюда
// приходит уже готовая строка, не история сообщений целиком, см.
// internal/agent.buildRagQuery). top_k — сколько кандидатов вернуть,
// решает вызывающая сторона (не хардкодится на стороне Python), чтобы
// смена значения не требовала передеплоя helper/.
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryText     string                 `protobuf:"bytes,1,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_zan_rpc_v1_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zan_rpc_v1_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_zan_rpc_v1_rag_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

// SearchMatch — кандидат-источник: ref/quote — та же форма, что
// domain.Source в Go (zan-backend-tz-v2.md §2.7: "[{ref, quote}]") — Go
// сверяет то, что процитировала LLM, с этим списком (verifySources,
// backend-roadmap.md §1.4 "риск"), не с сырым текстом чанка. score —
// оценка релевантности (cosine similarity, 0..1, выше — релевантнее) —
// Go сам решает, что из кандидатов реально положить в промпт (BACKEND_PLAN.md
// §1.1: "Go сам решает, что из этого передать в промпт LLM"), Python не
// фильтрует и не обрезает список сверх top_k.
type SearchMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Quote         string                 `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMatch) Reset() {
	*x = SearchMatch{}
	mi := &file_zan_rpc_v1_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMatch) ProtoMessage() {}

func (x *SearchMatch) ProtoReflect() protoreflect.Message {
	mi := &file_zan_rpc_v1_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMatch.ProtoReflect.Descriptor instead.
func (*SearchMatch) Descriptor() ([]byte, []int) {
	return file_zan_rpc_v1_rag_proto_rawDescGZIP(), []int{1}
}

func (x *SearchMatch) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *SearchMatch) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

func (x *SearchMatch) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// SearchResponse.matches — пустой список (не ошибка) — легитимный исход,
// когда в корпусе ничего релевантного не нашлось; Go в этом случае просто
// вызывает LLM без RAG-контекста (деградация, не блокировка, см.
// grpcclient.IsUnavailable — но это другой случай: helper ответил, просто
// нечем).
type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*SearchMatch         `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_zan_rpc_v1_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zan_rpc_v1_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_zan_rpc_v1_rag_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetMatches() []*SearchMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

var File_zan_rpc_v1_rag_proto protoreflect.FileDescriptor

const file_zan_rpc_v1_rag_proto_rawDesc = "" +
	"\n" +
	"\x14zan/rpc/v1/rag.proto\x12\n" +
	"zan.rpc.v1\"C\n" +
	"\rSearchRequest\x12\x1d\n" +
	"\n" +
	"query_text\x18\x01 \x01(\tR\tqueryText\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\"K\n" +
	"\vSearchMatch\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x14\n" +
	"\x05quote\x18\x02 \x01(\tR\x05quote\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\"C\n" +
	"\x0eSearchResponse\x121\n" +
	"\amatches\x18\x01 \x03(\v2\x17.zan.rpc.v1.SearchMatchR\amatches2M\n" +
	"\n" +
	"RagService\x12?\n" +
	"\x06Search\x12\x19.zan.rpc.v1.SearchRequest\x1a\x1a.zan.rpc.v1.SearchResponseB0Z.zan-backend/internal/genproto/zan/rpc/v1;zanv1b\x06proto3"

var (
	file_zan_rpc_v1_rag_proto_rawDescOnce sync.Once
	file_zan_rpc_v1_rag_proto_rawDescData []byte
)

func file_zan_rpc_v1_rag_proto_rawDescGZIP() []byte {
	file_zan_rpc_v1_rag_proto_rawDescOnce.Do(func() {
		file_zan_rpc_v1_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zan_rpc_v1_rag_proto_rawDesc), len(file_zan_rpc_v1_rag_proto_rawDesc)))
	})
	return file_zan_rpc_v1_rag_proto_rawDescData
}

var file_zan_rpc_v1_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_zan_rpc_v1_rag_proto_goTypes = []any{
	(*SearchRequest)(nil),  // 0: zan.rpc.v1.SearchRequest
	(*SearchMatch)(nil),    // 1: zan.rpc.v1.SearchMatch
	(*SearchResponse)(nil), // 2: zan.rpc.v1.SearchResponse
}
var file_zan_rpc_v1_rag_proto_depIdxs = []int32{
	1, // 0: zan.rpc.v1.SearchResponse.matches:type_name -> zan.rpc.v1.SearchMatch
	0, // 1: zan.rpc.v1.RagService.Search:input_type -> zan.rpc.v1.SearchRequest
	2, // 2: zan.rpc.v1.RagService.Search:output_type -> zan.rpc.v1.SearchResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_zan_rpc_v1_rag_proto_init() }
func file_zan_rpc_v1_rag_proto_init() {
	if File_zan_rpc_v1_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zan_rpc_v1_rag_proto_rawDesc), len(file_zan_rpc_v1_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zan_rpc_v1_rag_proto_goTypes,
		DependencyIndexes: file_zan_rpc_v1_rag_proto_depIdxs,
		MessageInfos:      file_zan_rpc_v1_rag_proto_msgTypes,
	}.Build()
	File_zan_rpc_v1_rag_proto = out.File
	file_zan_rpc_v1_rag_proto_goTypes = nil
	file_zan_rpc_v1_rag_proto_depIdxs = nil
}
