// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: zan/rpc/v1/stt.proto

package zanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TranscribeRequest — file_url по тому же принципу, что ExtractRequest
// (files.proto). lang — необязательная подсказка провайдеру
// (domain.Session.Language на стороне Go, BACKEND_PLAN.md §6 п.2);
// LANG_UNSPECIFIED — провайдер определяет язык сам.
type TranscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUrl       string                 `protobuf:"bytes,1,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Lang          Lang                   `protobuf:"varint,3,opt,name=lang,proto3,enum=zan.rpc.v1.Lang" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeRequest) Reset() {
	*x = TranscribeRequest{}
	mi := &file_zan_rpc_v1_stt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeRequest) ProtoMessage() {}

func (x *TranscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zan_rpc_v1_stt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeRequest.ProtoReflect.Descriptor instead.
func (*TranscribeRequest) Descriptor() ([]byte, []int) {
	return file_zan_rpc_v1_stt_proto_rawDescGZIP(), []int{0}
}

func (x *TranscribeRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *TranscribeRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *TranscribeRequest) GetLang() Lang {
	if x != nil {
		return x.Lang
	}
	return Lang_LANG_UNSPECIFIED
}

// TranscribeResponse.text — уже обрезанный/тримленный текст. Пустая строка
// (тишина) — не ошибка на этом уровне, backend решает, что с ней делать
// (zan-backend-tz-v3.md §5.4: "не расслышал, повторите").
type TranscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeResponse) Reset() {
	*x = TranscribeResponse{}
	mi := &file_zan_rpc_v1_stt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeResponse) ProtoMessage() {}

func (x *TranscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zan_rpc_v1_stt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeResponse.ProtoReflect.Descriptor instead.
func (*TranscribeResponse) Descriptor() ([]byte, []int) {
	return file_zan_rpc_v1_stt_proto_rawDescGZIP(), []int{1}
}

func (x *TranscribeResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_zan_rpc_v1_stt_proto protoreflect.FileDescriptor

const file_zan_rpc_v1_stt_proto_rawDesc = "" +
	"\n" +
	"\x14zan/rpc/v1/stt.proto\x12\n" +
	"zan.rpc.v1\x1a\x17zan/rpc/v1/common.proto\"q\n" +
	"\x11TranscribeRequest\x12\x19\n" +
	"\bfile_url\x18\x01 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12$\n" +
	"\x04lang\x18\x03 \x01(\x0e2\x10.zan.rpc.v1.LangR\x04lang\"(\n" +
	"\x12TranscribeResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text2Y\n" +
	"\n" +
	"SttService\x12K\n" +
	"\n" +
	"Transcribe\x12\x1d.zan.rpc.v1.TranscribeRequest\x1a\x1e.zan.rpc.v1.TranscribeResponseB0Z.zan-backend/internal/genproto/zan/rpc/v1;zanv1b\x06proto3"

var (
	file_zan_rpc_v1_stt_proto_rawDescOnce sync.Once
	file_zan_rpc_v1_stt_proto_rawDescData []byte
)

func file_zan_rpc_v1_stt_proto_rawDescGZIP() []byte {
	file_zan_rpc_v1_stt_proto_rawDescOnce.Do(func() {
		file_zan_rpc_v1_stt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zan_rpc_v1_stt_proto_rawDesc), len(file_zan_rpc_v1_stt_proto_rawDesc)))
	})
	return file_zan_rpc_v1_stt_proto_rawDescData
}

var file_zan_rpc_v1_stt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_zan_rpc_v1_stt_proto_goTypes = []any{
	(*TranscribeRequest)(nil),  // 0: zan.rpc.v1.TranscribeRequest
	(*TranscribeResponse)(nil), // 1: zan.rpc.v1.TranscribeResponse
	(Lang)(0),                  // 2: zan.rpc.v1.Lang
}
var file_zan_rpc_v1_stt_proto_depIdxs = []int32{
	2, // 0: zan.rpc.v1.TranscribeRequest.lang:type_name -> zan.rpc.v1.Lang
	0, // 1: zan.rpc.v1.SttService.Transcribe:input_type -> zan.rpc.v1.TranscribeRequest
	1, // 2: zan.rpc.v1.SttService.Transcribe:output_type -> zan.rpc.v1.TranscribeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_zan_rpc_v1_stt_proto_init() }
func file_zan_rpc_v1_stt_proto_init() {
	if File_zan_rpc_v1_stt_proto != nil {
		return
	}
	file_zan_rpc_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zan_rpc_v1_stt_proto_rawDesc), len(file_zan_rpc_v1_stt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zan_rpc_v1_stt_proto_goTypes,
		DependencyIndexes: file_zan_rpc_v1_stt_proto_depIdxs,
		MessageInfos:      file_zan_rpc_v1_stt_proto_msgTypes,
	}.Build()
	File_zan_rpc_v1_stt_proto = out.File
	file_zan_rpc_v1_stt_proto_goTypes = nil
	file_zan_rpc_v1_stt_proto_depIdxs = nil
}
