// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: zan/rpc/v1/stt.proto

package zanv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SttService_Transcribe_FullMethodName = "/zan.rpc.v1.SttService/Transcribe"
)

// SttServiceClient is the client API for SttService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SttService — распознавание речи (BACKEND_PLAN.md §3, Stage 4). Вызывается
// синхронно из POST /voice/transcribe (zan-backend-tz-v2.md §4.7) — клиент
// ждёт текст до отправки сообщения в тред.
type SttServiceClient interface {
	Transcribe(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (*TranscribeResponse, error)
}

type sttServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSttServiceClient(cc grpc.ClientConnInterface) SttServiceClient {
	return &sttServiceClient{cc}
}

func (c *sttServiceClient) Transcribe(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (*TranscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranscribeResponse)
	err := c.cc.Invoke(ctx, SttService_Transcribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SttServiceServer is the server API for SttService service.
// All implementations must embed UnimplementedSttServiceServer
// for forward compatibility.
//
// SttService — распознавание речи (BACKEND_PLAN.md §3, Stage 4). Вызывается
// синхронно из POST /voice/transcribe (zan-backend-tz-v2.md §4.7) — клиент
// ждёт текст до отправки сообщения в тред.
type SttServiceServer interface {
	Transcribe(context.Context, *TranscribeRequest) (*TranscribeResponse, error)
	mustEmbedUnimplementedSttServiceServer()
}

// UnimplementedSttServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSttServiceServer struct{}

func (UnimplementedSttServiceServer) Transcribe(context.Context, *TranscribeRequest) (*TranscribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Transcribe not implemented")
}
func (UnimplementedSttServiceServer) mustEmbedUnimplementedSttServiceServer() {}
func (UnimplementedSttServiceServer) testEmbeddedByValue()                    {}

// UnsafeSttServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SttServiceServer will
// result in compilation errors.
type UnsafeSttServiceServer interface {
	mustEmbedUnimplementedSttServiceServer()
}

func RegisterSttServiceServer(s grpc.ServiceRegistrar, srv SttServiceServer) {
	// If the following call panics, it indicates UnimplementedSttServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SttService_ServiceDesc, srv)
}

func _SttService_Transcribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SttServiceServer).Transcribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SttService_Transcribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SttServiceServer).Transcribe(ctx, req.(*TranscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SttService_ServiceDesc is the grpc.ServiceDesc for SttService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SttService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zan.rpc.v1.SttService",
	HandlerType: (*SttServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Transcribe",
			Handler:    _SttService_Transcribe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zan/rpc/v1/stt.proto",
}
